main: de.dopemc.hardcore.statsapi.Main
name: DopeMC-StatsAPI
version: 1.0.0
author: Dennis Michanosin
api-version: 1.21
commands:
  stats:
    description: Zeigt deine Statistiken an oder die eines anderen Spielers (Admin).
permissions:
  dopemc.statsapi.admin:
    description: Ermöglicht das Anzeigen und Verwalten von Statistiken anderer Spieler.
    default: op